import{a as m,S as $,i as u}from"./assets/vendor-Rdv7LHNr.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const y=(e,r)=>{const s=document.querySelector(".gallery");if(e.length===0){iziToast.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const a=e.map(({webformatURL:t,largeImageURL:o,tags:n,likes:h,views:L,comments:q,downloads:S},w)=>`
              <li class="gallery-item">
                  <a href="${o}" class="gallery-link">
                      <img src="${t}" alt="${n}" class="gallery-image" id="image-${r}-${w}"/>
                  </a>
                  <div class="info">
                      <p class="info-item"><span class="info-item-total">Likes</span> ${h}</p>
                      <p class="info-item"><span class="info-item-total">Views</span> ${L}</p>
                      <p class="info-item"><span class="info-item-total">Comments</span> ${q}</p>
                      <p class="info-item"><span class="info-item-total">Downloads</span> ${S}</p>
                  </div>
              </li>
          `).join("");s.insertAdjacentHTML("beforeend",a)},b=()=>{const e=document.querySelector(".loader");e.style.display="block"},x=()=>{const e=document.querySelector(".loader-next");e.style.display="flex"},f=()=>{const e=document.querySelector(".loader");e.style.display="none"},E=()=>{const e=document.querySelector(".loader-next");e.style.display="none"},N="46054867-15d582c16d4d1b2cce4772636",P="https://pixabay.com/api/";m.defaults.baseURL=P;let c=15;const p=async(e,r)=>{try{const s=new URLSearchParams({per_page:c,page:r}),t=(await m.get(`?key=${N}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&${s}`)).data,o=Math.ceil(t.totalHits/c);if(r>o)return E(),iziToast.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."});if(t.hits.length===0)throw new Error("No images found for this query.");return t.hits}catch(s){throw console.error(`Error fetching images: ${s.message}`),s}},d=document.querySelector(".form"),v=document.querySelector(".gallery"),g=new $(".gallery a",{captionsData:"alt",captionDelay:250}),O=document.querySelector(".btn");let i=1,l="";d.addEventListener("submit",e=>{e.preventDefault(),l=e.target.elements.query.value.trim(),l&&(v.innerHTML="",i=1,b(),p(l,i).then(r=>{i+=1,y(r),g.refresh()}).catch(r=>{console.error(r),u.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}).finally(()=>{f(),x()}),d.reset())});O.addEventListener("click",async()=>{i+=1;try{const e=await p(l,i);if(e.length===0)return u.error({title:"Error",message:"No more images to load."});y(e),g.refresh();const r=document.querySelector(".gallery-item");if(r){const s=r.getBoundingClientRect().height;window.scrollBy({top:s*2,left:0,behavior:"smooth"})}}catch(e){console.log(e)}finally{f()}});
//# sourceMappingURL=index.js.map
