import{a as m,S as w,i as b}from"./assets/vendor-Rdv7LHNr.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const y=(e,r)=>{const a=document.querySelector(".gallery");if(e.length===0){iziToast.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=e.map(({webformatURL:t,largeImageURL:o,tags:n,likes:h,views:L,comments:q,downloads:S},$)=>`
              <li class="gallery-item">
                  <a href="${o}" class="gallery-link">
                      <img src="${t}" alt="${n}" class="gallery-image" id="image-${r}-${$}"/>
                  </a>
                  <div class="info">
                      <p class="info-item"><span class="info-item-total">Likes</span> ${h}</p>
                      <p class="info-item"><span class="info-item-total">Views</span> ${L}</p>
                      <p class="info-item"><span class="info-item-total">Comments</span> ${q}</p>
                      <p class="info-item"><span class="info-item-total">Downloads</span> ${S}</p>
                  </div>
              </li>
          `).join("");a.insertAdjacentHTML("beforeend",s)},x=()=>{const e=document.querySelector(".loader");e.style.display="block"},E=()=>{const e=document.querySelector(".loader-next");e.style.display="flex"},f=()=>{const e=document.querySelector(".loader");e.style.display="none"},P=()=>{const e=document.querySelector(".loader-next");e.style.display="none"},v="46054867-15d582c16d4d1b2cce4772636",N="https://pixabay.com/api/";m.defaults.baseURL=N;let c=1,d=15;const p=async e=>{try{const r=new URLSearchParams({per_page:d,page:c}),s=(await m.get(`?key=${v}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&${r}`)).data,t=Math.ceil(s.totalHits/d);if(c>t)return P(),iziToast.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."});if(s.hits.length===0)throw new Error("No images found for this query.");return s.hits}catch(r){throw console.error(`Error fetching images: ${r.message}`),r}},u=document.querySelector(".form"),O=document.querySelector(".gallery"),g=new w(".gallery a",{captionsData:"alt",captionDelay:250}),I=document.querySelector(".btn");let l=1,i="";u.addEventListener("submit",e=>{e.preventDefault(),i=e.target.elements.query.value.trim(),i&&(O.innerHTML="",l=1,x(),p(i).then(r=>{y(r),g.refresh(),l+=1}).catch(r=>{console.error(r),b.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}).finally(()=>{f(),E()}),u.reset())});I.addEventListener("click",async()=>{try{const e=await p(i,l);y(e),g.refresh(),l+=1;const r=document.querySelector(".gallery-item");if(r){const a=r.getBoundingClientRect().height;window.scrollBy({top:a*2,left:0,behavior:"smooth"})}}catch(e){console.log(e)}finally{f()}});
//# sourceMappingURL=index.js.map
